name = "felishae"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "45.60.186.91"
UUID = "0ffdec90-072d-420c-8dce-414b8c72f821"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
